### ISSUE TITLE
Rules.js会造成dns泄露

### ISSUE THREAD

**Issue by letterk** [abrclano/Self-use-Rules#1]
[Rules.js](https://github.com/abrclano/Self-use-Rules/blob/main/Clash.verge/Rules.js)无修改
非常奇怪, 在fakeip模式下依然会使用国内dns
![Snipaste_2023-12-17_14-46-07](https://github.com/abrclano/Self-use-Rules/assets/9822709/64737a2e-2d2e-4b61-a1a2-dc8a1a9bd48c)

---

我使用以下的配置, 不会泄露
```yaml
geodata-mode: true
tcp-concurrent: true
geox-url:
  geoip: https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat
  geosite: https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat
  mmdb: https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb
dns:
  enable: true
  prefer-h3: false
  listen: 0.0.0.0:1053
  ipv6: true
  default-nameserver:
    - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - +.lan
    - +.local
    - localhost.ptlogin2.qq.com
  nameserver-policy:
    geosite:category-ads-all: rcode://success
  nameserver:
    - dhcp://auto
    - 192.168.31.1
    - 223.5.5.5
    - tls://dot.pub
    - https://dns.alidns.com/dns-query
```
![image](https://github.com/abrclano/Self-use-Rules/assets/9822709/86e8d6cc-3bd6-4a1d-8d40-9ddc65ba0199)

---

另外使用[Mixin.yaml](https://github.com/abrclano/Self-use-Rules/blob/main/Clash.verge/Mixin.yaml)合并规则, 不会造成泄露
