### ISSUE TITLE
[enhancement]大佬，Auto组加入Proxy组，然后Proxy默认选定Auto组能实现吗？

### ISSUE THREAD

**Issue by lanceyliao** [abrclano/Self-use-Rules#3]
https://github.com/abrclano/Meandering.Path/blob/538088e3dd5b837f6d8d4afd4b11e06e3c2b37e0/Clash.verge/Script/Rules.js#L144

**Comment by lanceyliao** [comment]
https://github.com/abrclano/Meandering.Path/blob/538088e3dd5b837f6d8d4afd4b11e06e3c2b37e0/Clash.verge/Script/Rules.js#L100
https://github.com/abrclano/Meandering.Path/blob/538088e3dd5b837f6d8d4afd4b11e06e3c2b37e0/Clash.verge/Script/Rules.js#L101
https://github.com/abrclano/Meandering.Path/blob/538088e3dd5b837f6d8d4afd4b11e06e3c2b37e0/Clash.verge/Script/Rules.js#L102

**Comment by abrclano** [comment]
```
const Proxy = { name: "Proxy", type: "select", proxies: ["Auto", ...(allProxies.length > 0 ? allProxies : ["DIRECT"])], icon: "https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Proxy.png" };
```
或者
```
const Proxy = { name: "Proxy", type: "select", proxies: (allProxies.length > 0 ? allProxies : ["DIRECT"]).concat("Auto"), icon: "https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Proxy.png" };
```
都可以，前者把`Auto`添加到`Proxy`分组的最前面，后者添加到分组的最后面，因为是`select`属性，所以默认选定`Auto`可能做不到，只能手动选择一下

**Comment by lanceyliao** [comment]
谢谢大佬，这边改成第一种了，这样Auto默认在第一个可选项

**Comment by lanceyliao** [comment]
这段正则看看有没有能参考的？
```
exclude_remarks = (公益|流量|时间|过期|无效|注册|回国|产品|免费|体验|广告位|请|群|官?网[站址]?|等级[12]|[vV](ip|IP)?[01])
```

**Comment by abrclano** [comment]
正则的话要看机场和个人使用需求，每个人的需求可能不一样，所以fork了改成适合自己的就行了，因为我的这个仓库也只是方便自己跨设备使用才弄的

**Comment by lanceyliao** [comment]
大佬，这是我之前clash mixin的配置，有好几个nameserver，想加进来是加在哪一行？
https://github.com/abrclano/Meandering.Path/blob/538088e3dd5b837f6d8d4afd4b11e06e3c2b37e0/Clash.verge/Merge/Mixin.yaml#L57
还是
https://github.com/abrclano/Meandering.Path/blob/538088e3dd5b837f6d8d4afd4b11e06e3c2b37e0/Clash.verge/Merge/Mixin.yaml#L60
还是
https://github.com/abrclano/Meandering.Path/blob/538088e3dd5b837f6d8d4afd4b11e06e3c2b37e0/Clash.verge/Merge/Mixin.yaml#L62

```
mixin: # object
  dns:
    enable: true # 是否启用dns false
    ipv6: true # 开启 IPV6
    listen: 0.0.0.0:53 # dns 监听
    enhanced-mode: fake-ip # 模式：redir-host或fake-ip
    fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
    fake-ip-filter: # fake ip 白名单列表，如果你不知道这个参数的作用，请勿修改
      - "*.lan"
      - http://localhost.ptlogin2.qq.com/
      - +.srv.nintendo.net
      - +.stun.playstation.net
      - +.msftconnecttest.com
      - +.msftncsi.com
      - +.xboxlive.com
      - http://msftconnecttest.com/
      - xbox.*.microsoft.com
      - "*.battlenet.com.cn"
      - "*.battlenet.com"
      - "*.blzstatic.cn"
      - "*.battle.net"
    nameserver:
      - 223.5.5.5 # 阿里DNS
      - 180.76.76.76 # 百度DNS
      - 119.29.29.29 # 腾讯DNS
      - 117.50.10.10 # ONE DNS纯净版 直接返回其真实的响应结果
      - 114.114.114.114 # 114DNS
      - https://dns.alidns.com/dns-query # 阿里 DoH DNS
      - https://doh.360.cn/dns-query # 360 DoH DNS
    fallback:
      - 1.1.1.1
      - 8.8.8.8 # 谷歌DNS
      - tls://dns.rubyfish.cn:853
      - tls://1.0.0.1:853
      - tls://dns.google:853
      - https://dns.rubyfish.cn/dns-query
      - https://cloudflare-dns.com/dns-query
      - https://dns.google/dns-query
    fallback-filter:
      geoip: true # 默认
      geoip-code: CN
      ipcidr:
        - 240.0.0.0/4
```
